CHANGELOG.md

Please make sure to keep this updated when we release every version.

docs: add the missing changlog for v0.7.0

---

console/src/main/java/org/nervos/ckb/RpcRequest.java
core/src/main/java/org/nervos/ckb/methods/type/Header.java
core/src/main/java/org/nervos/ckb/methods/type/Script.java
core/src/main/java/org/nervos/ckb/service/CKBApi.java
core/src/main/java/org/nervos/ckb/service/JsonRpcCKBApiImpl.java
core/src/test/java/type/ScriptTest.java

* Remove several version field
* Change field type long or int to String

feat: Change RPC types per CKB change

---

utils/src/main/java/org/nervos/ckb/crypto/secp256k1/Sign.java
utils/src/test/java/org/nervos/ckb/address/AddressTest.java
utils/src/test/java/org/nervos/ckb/crypto/secp256k1/SignTest.java

* Set generating compressed public key from private key as the default
* Add more test cases for secp256k1 and address

test: add more test cases for secp256k1

---

console/src/main/java/org/nervos/ckb/RpcRequest.java
core/src/main/java/org/nervos/ckb/methods/response/CkbTransaction.java
core/src/main/java/org/nervos/ckb/methods/type/TransactionWithStatus.java

* Update `get_transaction` rpc response

feat: update get_transaction rpc

---

console/src/main/java/org/nervos/ckb/RpcRequest.java
console/src/test/java/org/nervos/ckb/RpcRequestTest.java
core/src/main/java/org/nervos/ckb/service/CKBApi.java
core/src/main/java/org/nervos/ckb/service/JsonRpcCKBApiImpl.java

* Add get_block_by_number rpc
* Add rpc test and test with local ckb node

chore: add get_block_by_number rpc and add rpc test

---

console/src/main/java/org/nervos/ckb/RpcRequest.java
console/src/test/java/org/nervos/ckb/RpcRequestTest.java
core/src/main/java/org/nervos/ckb/service/CKBApi.java
core/src/main/java/org/nervos/ckb/service/JsonRpcCKBApiImpl.java

* Add get_block_by_number rpc
* Add rpc test and test with local ckb node

[ᚬrc/v0.11.0] chore: add get_block_by_number rpc and add rpc test

---

console/src/main/java/org/nervos/ckb/RpcRequest.java
console/src/test/java/org/nervos/ckb/RpcRequestTest.java
core/src/main/java/org/nervos/ckb/methods/response/CkbEpoch.java
core/src/main/java/org/nervos/ckb/methods/type/Epoch.java
core/src/main/java/org/nervos/ckb/methods/type/Header.java
core/src/main/java/org/nervos/ckb/service/CKBApi.java
core/src/main/java/org/nervos/ckb/service/JsonRpcCKBApiImpl.java

* Implement get current epoch rpc

feat: implement get current epoch rpc

---

README.md

* Add Prerequisites and Installation and Usage for README

docs: add Prerequisites and Installation and Usage for README

---

console/src/main/java/org/nervos/ckb/RpcRequest.java
console/src/test/java/org/nervos/ckb/RpcRequestTest.java
core/src/main/java/org/nervos/ckb/service/CKBApi.java
core/src/main/java/org/nervos/ckb/service/JsonRpcCKBApiImpl.java

* Implement get epoch by number rpc

feat: implement get epoch by number rpc

---

core/src/main/java/org/nervos/ckb/methods/type/Header.java

* Rename proposals_root to proposals_hash

Rename proposals_root to proposals_hash

---

console/src/main/java/org/nervos/ckb/RpcRequest.java
console/src/test/java/org/nervos/ckb/RpcRequestTest.java
core/src/main/java/org/nervos/ckb/methods/response/CkbBlockchainInfo.java
core/src/main/java/org/nervos/ckb/methods/response/CkbPeersState.java
core/src/main/java/org/nervos/ckb/methods/type/BlockchainInfo.java
core/src/main/java/org/nervos/ckb/methods/type/PeerState.java
core/src/main/java/org/nervos/ckb/service/CKBApi.java
core/src/main/java/org/nervos/ckb/service/JsonRpcCKBApiImpl.java

* Implement get_blockchain_info rpc
* Implement get_peers_state rpc

Implement state info rpc

---

console/src/main/java/org/nervos/ckb/RpcRequest.java
console/src/test/java/org/nervos/ckb/RpcRequestTest.java
core/src/main/java/org/nervos/ckb/methods/response/CkbCycles.java
core/src/main/java/org/nervos/ckb/methods/type/Cycles.java
core/src/main/java/org/nervos/ckb/methods/type/Transaction.java
core/src/main/java/org/nervos/ckb/service/CKBApi.java
core/src/main/java/org/nervos/ckb/service/JsonRpcCKBApiImpl.java

* Implement dry_run_transaction rpc

feat: implement dry_run_transaction rpc

---

console/src/main/java/org/nervos/ckb/example/TransactionExample.java
console/src/test/java/org/nervos/ckb/example/TransactionExampleTest.java

make nodeUrl to be param in TransactionExample

fix: nodeUrl as param

---

core/src/main/java/org/nervos/ckb/methods/type/Transaction.java
core/src/test/java/type/TransactionTest.java

*  Implement Secp256k1 recoverable sign

feat(ui): Implement Secp256k1 recoverable sign

---

core/src/main/java/org/nervos/ckb/methods/response/CkbBannedAddresses.java
core/src/main/java/org/nervos/ckb/methods/response/CkbBannedResult.java
core/src/main/java/org/nervos/ckb/methods/response/CkbBannedResultAddresses.java
core/src/main/java/org/nervos/ckb/methods/response/CkbCellbaseOutputCapacity.java
core/src/main/java/org/nervos/ckb/methods/type/BannedAddress.java
core/src/main/java/org/nervos/ckb/methods/type/BannedResultAddress.java
core/src/main/java/org/nervos/ckb/methods/type/CellbaseOutputCapacity.java
core/src/main/java/org/nervos/ckb/methods/type/Header.java
core/src/main/java/org/nervos/ckb/service/CKBApi.java
core/src/main/java/org/nervos/ckb/service/JsonRpcCKBApiImpl.java
core/src/test/java/service/RpcRequestTest.java

* `get_cellbase_output_capacity_details`
* `get_header`
* `get_header_by_number`
* `set_ban`
* `get_banned_address`

[ᚬrc/v0.17.0] Add new chain and net rpcs

---

core/src/main/java/org/nervos/ckb/methods/response/CkbBannedAddresses.java
core/src/main/java/org/nervos/ckb/methods/response/CkbBannedResult.java
core/src/main/java/org/nervos/ckb/methods/response/CkbBannedResultAddresses.java
core/src/main/java/org/nervos/ckb/methods/response/CkbCellbaseOutputCapacity.java
core/src/main/java/org/nervos/ckb/methods/type/BannedAddress.java
core/src/main/java/org/nervos/ckb/methods/type/BannedResultAddress.java
core/src/main/java/org/nervos/ckb/methods/type/CellbaseOutputCapacity.java
core/src/main/java/org/nervos/ckb/methods/type/Header.java
core/src/main/java/org/nervos/ckb/service/CKBApi.java
core/src/main/java/org/nervos/ckb/service/JsonRpcCKBApiImpl.java
core/src/test/java/service/RpcRequestTest.java

* `get_cellbase_output_capacity_details`
* `get_header`
* `get_header_by_number`
* `set_ban`
* `get_banned_address`

Add chain and net rpcs

---

CHANGELOG.md
build.gradle
console/src/main/java/org/nervos/ckb/Wallet.java
core/src/main/java/org/nervos/ckb/methods/type/Script.java
core/src/main/java/org/nervos/ckb/system/SystemContract.java
core/src/test/java/system/SystemContractTest.java
core/src/test/java/type/ScriptTest.java

* Fix script hash bug([342365c](https://github.com/nervosnetwork/ckb-sdk-java/commit/342365c488bb4dfee751bbabaf4e1dc6dc3592c9))

[ᚬmaster] Hotfix script hash

---

.travis.yml
build.gradle
console/src/main/java/org/nervos/ckb/TransactionExample.java
core/src/main/java/org/nervos/ckb/methods/response/CkbBlockNumber.java
core/src/main/java/org/nervos/ckb/methods/type/Header.java
core/src/main/java/org/nervos/ckb/methods/type/NodeInfo.java
core/src/main/java/org/nervos/ckb/service/JsonRpcCKBApiImpl.java
core/src/main/java/org/nervos/ckb/system/SystemContract.java
core/src/main/java/org/nervos/ckb/transaction/CellGatherer.java
core/src/main/java/org/nervos/ckb/transaction/TxGenerator.java
core/src/main/java/org/nervos/ckb/utils/Convert.java
core/src/main/java/org/nervos/ckb/utils/Serializer.java
core/src/test/java/service/RpcRequestTest.java
core/src/test/java/system/SystemContractTest.java
core/src/test/java/type/ScriptTest.java
core/src/test/java/type/TransactionTest.java
serialization/src/main/java/org/nervos/ckb/type/fixed/UInt32.java
serialization/src/main/java/org/nervos/ckb/type/fixed/UInt64.java
serialization/src/test/java/type/Byte1Test.java
serialization/src/test/java/type/FixedTest.java
serialization/src/test/java/type/UInt32Test.java
utils/src/main/java/org/nervos/ckb/utils/Numeric.java
utils/src/test/java/org/nervos/ckb/crypto/secp256k1/SignTest.java
utils/src/test/java/org/nervos/ckb/utils/NumericTest.java
utils/src/test/java/org/nervos/ckb/utils/StringsTest.java

* Update integer to hex string
* Fix junit config of `bugild.gradle` and update related test cases 
* Update transaction generator, serializer and test cases with integer

feat: Update integer to hex string

---

build.gradle
core/src/main/java/org/nervos/ckb/service/RpcService.java
core/src/main/java/org/nervos/ckb/type/Epoch.java
core/src/main/java/org/nervos/ckb/type/Header.java

BREAKING CHANGE:
- Replace difficulty with compact_target of epoch
- Remove difficulty, witnesses_root and uncles_count and add compact_target of header
Feature: 
- Update build.gradle test config
- Update okhttp logger config

feat: Compact header

---

build.gradle
console/src/main/java/org/nervos/ckb/example/RpcExample.java
core/src/main/java/org/nervos/ckb/service/Api.java
core/src/main/java/org/nervos/ckb/service/RpcService.java
core/src/main/java/org/nervos/ckb/transaction/CellCollector.java
core/src/test/java/service/ApiTest.java
core/src/test/java/type/ScriptTest.java
core/src/test/java/type/TransactionTest.java

* move exception to outside application
* update the version of publishing jar to maven

refactor: move exception to outside application

---

console/src/main/java/org/nervos/ckb/example/TransactionExample.java
core/src/main/java/org/nervos/ckb/service/Api.java
core/src/main/java/org/nervos/ckb/type/FeeRate.java
core/src/main/java/org/nervos/ckb/utils/Calculator.java
core/src/test/java/service/ApiTest.java

Add estimating fee rate for transaction

---

CHANGELOG.md
build.gradle
ckb/src/main/java/org/nervos/ckb/utils/address/AddressParser.java

I'm sorry 0.24.2 ~ 0.24.4 did't upload jar successfully to maven server because of my poor network. 
Now v0.24.5 can work well in the maven server, so I need submit a new version to release. 
Thanks.

[ᚬmaster] Rc/v0.24.5

---

CHANGELOG.md
README.md
build.gradle

* Update ckb-sdk build.gradle for packing ([d0824ee](https://github.com/nervosnetwork/ckb-sdk-java/commit/d0824ee7d68fa76eb0db35172e9d052d9d205662))

[ᚬmaster] Rc/v0.25.0

---

example/src/main/java/org/nervos/ckb/MultiKeySingleSigTxExample.java
example/src/main/java/org/nervos/ckb/MultiSignTransactionExample.java
example/src/main/java/org/nervos/ckb/SendToMultiSigAddressTxExample.java
example/src/main/java/org/nervos/ckb/SingleKeySingleSigTxExample.java
example/src/main/java/org/nervos/ckb/SingleSigWithIndexerTxExample.java
example/src/main/java/org/nervos/ckb/transaction/CellCollector.java
example/src/main/java/org/nervos/ckb/transaction/CellCollectorWithIndexer.java
example/src/main/java/org/nervos/ckb/transaction/CollectResult.java
example/src/main/java/org/nervos/ckb/transaction/CollectUtils.java

- Update change output capacity after collecting cells
- Refactor examples to read message more clearly

Refactor cell collector

---

ckb/src/main/java/org/nervos/ckb/transaction/TransactionBuilder.java
example/src/main/java/org/nervos/ckb/MultiKeySingleSigTxExample.java
example/src/main/java/org/nervos/ckb/MultiSignTransactionExample.java
example/src/main/java/org/nervos/ckb/NervosDaoExample.java
example/src/main/java/org/nervos/ckb/SendToMultiSigAddressTxExample.java
example/src/main/java/org/nervos/ckb/SingleKeySingleSigTxExample.java
example/src/main/java/org/nervos/ckb/SingleSigWithIndexerTxExample.java
example/src/main/java/org/nervos/ckb/transaction/CellCollector.java
example/src/main/java/org/nervos/ckb/transaction/CellCollectorWithIndexer.java
example/src/main/java/org/nervos/ckb/transaction/CollectUtils.java

- Refactor CellCollector collectInputs whose parameters include transaction not outputs
- Rename example private keys and address

Refactor collectInputs parameters and method

---

CHANGELOG.md
build.gradle

* Remove useless code ([557632a](https://github.com/nervosnetwork/ckb-sdk-java/commit/557632aef474d7ff310a83e292f117b0502dbdba))

[ᚬmaster] Rc/v0.26.0

---

ckb/src/main/java/org/nervos/ckb/service/Api.java
ckb/src/main/java/org/nervos/ckb/type/BlockEconomicState.java
ckb/src/main/java/org/nervos/ckb/type/TxPoolInfo.java
ckb/src/test/java/service/ApiTest.java

- add get_block_economic_state rpc
- add min_tx_fee to tx_pool_info rpc

Add new rpc

---

.github/workflows/gradle.yml
CHANGELOG.md
README.md
build.gradle

* Update cell collector error information ([1468d85](https://github.com/nervosnetwork/ckb-sdk-java/commit/1468d850597ff89be5e6daeb654c5eabdbf39e06))
* Update output size calculating method ([3e7f6d8](https://github.com/nervosnetwork/ckb-sdk-java/commit/3e7f6d8cf955c30fc4e25d6718d3d60ae5447b34))

[ᚬmaster] Rc/v0.31.0

---

example/src/main/java/org/nervos/ckb/NervosDaoExample.java
example/src/main/java/org/nervos/ckb/SUDTExample.java
example/src/main/java/org/nervos/ckb/transaction/CellBlockIterator.java
example/src/main/java/org/nervos/ckb/transaction/CollectUtils.java
example/src/main/java/org/nervos/ckb/udt/UDTCellCollector.java
example/src/main/java/org/nervos/ckb/udt/UDTCollectResult.java
serialization/src/main/java/org/nervos/ckb/type/fixed/UInt128.java
serialization/src/test/java/type/UInt128Test.java
serialization/src/test/java/type/UInt64Test.java

Anyone-can-pay lock will be supported in another pr

Support sUDT with example

---

ckb-mercury-sdk/src/main/java/model/resp/GetBalanceResponse.java

public lock in GetBalanceResponse

fix: public lock

---

ckb-mercury-sdk/src/main/java/org/nervos/mercury/model/AdjustAccountPayloadBuilder.java
ckb-mercury-sdk/src/main/java/org/nervos/mercury/model/DaoClaimPayloadBuilder.java
ckb-mercury-sdk/src/main/java/org/nervos/mercury/model/DaoWithdrawPayloadBuilder.java
ckb-mercury-sdk/src/main/java/org/nervos/mercury/model/SudtIssuePayloadBuilder.java
ckb-mercury-sdk/src/main/java/org/nervos/mercury/model/req/payload/AdjustAccountPayload.java
ckb-mercury-sdk/src/main/java/org/nervos/mercury/model/req/payload/DaoClaimPayload.java
ckb-mercury-sdk/src/main/java/org/nervos/mercury/model/req/payload/DaoWithdrawPayload.java
ckb-mercury-sdk/src/main/java/org/nervos/mercury/model/req/payload/SudtIssuePayload.java
ckb-mercury-sdk/src/test/java/mercury/BuildSudtIssueTransactionTest.java
ckb-mercury-sdk/src/test/java/mercury/DaoTest.java

Update mercury RPC type following with https://github.com/nervosnetwork/mercury/pull/423

feat: Mercury RPC type update

---

ckb-mercury-sdk/src/main/java/org/nervos/mercury/model/req/payload/GetBalancePayload.java

feat: support field `extra` in mercury RPC `get_balance`

---

CHANGELOG.md
build.gradle
light-client/build.gradle

chore: 🤖 Release 2.1.0

---

CHANGELOG.md
build.gradle
ckb/src/main/java/org/nervos/ckb/CkbRpcApi.java
ckb/src/main/java/org/nervos/ckb/service/Api.java
ckb/src/test/java/service/ApiTest.java
core/src/main/java/org/nervos/ckb/type/BlockResponse.java
core/src/main/java/org/nervos/ckb/type/BlockWithCycles.java

- enable with_cycles parameter for get_block and get_block_by_number rpc

feat: 🎸 enable with_cycles of get_block and get_block_by_number

---

ckb/src/main/java/org/nervos/ckb/CkbRpcApi.java
ckb/src/main/java/org/nervos/ckb/service/Api.java
ckb/src/test/java/service/ApiTest.java
core/src/main/java/org/nervos/ckb/type/Block.java
core/src/main/java/org/nervos/ckb/type/PackedBlockWithCycles.java
core/src/main/java/org/nervos/ckb/type/PackedHeader.java
core/src/main/java/org/nervos/ckb/type/PackedTransactionWithStatus.java
core/src/main/java/org/nervos/ckb/utils/MoleculeConverter.java
serialization/src/main/java/org/nervos/ckb/type/concrete/Block.java
serialization/src/main/java/org/nervos/ckb/type/concrete/BlockV1.java
utils/src/main/java/org/nervos/ckb/utils/Numeric.java
utils/src/test/java/org/nervos/ckb/utils/NumericTest.java

1. Add packed version RPC.
2. Fix deserialization problem when with_cycle is false

Feat: packed rpcs

---

CHANGELOG.md

- prepare a new release to 2.1.1

docs: ✏️ Update CHANGELOG.md to prepare new release

---

build.gradle
light-client/build.gradle

- fix version in build.gradle from 2.1.0 to 2.1.1

chore: 🤖 change version to 2.1.1

---

ckb/src/main/java/org/nervos/ckb/CkbRpcApi.java
ckb/src/main/java/org/nervos/ckb/service/Api.java
ckb/src/test/java/service/ApiTest.java
core/src/main/java/org/nervos/ckb/type/MerkleProof.java
core/src/main/java/org/nervos/ckb/type/TransactionAndWitnessProof.java

Support rpc get_transaction_and_witness_proof and
verify_transaction_and_witness_proof

feat: 🎸 Add 2 rpcs: get_transaction_and_witness_proof and other

---

ckb/src/main/java/org/nervos/ckb/transaction/AbstractTransactionBuilder.java
ckb/src/main/java/org/nervos/ckb/transaction/CkbTransactionBuilder.java
ckb/src/main/java/org/nervos/ckb/transaction/SudtTransactionBuilder.java
ckb/src/main/java/org/nervos/ckb/transaction/TransactionBuilderConfiguration.java
ckb/src/main/java/org/nervos/ckb/transaction/handler/ScriptHandler.java
ckb/src/main/java/org/nervos/ckb/transaction/handler/TypIdHandler.java
ckb/src/test/java/transaction/CkbTransactionBuilderTest.java
core/src/main/java/org/nervos/ckb/sign/ScriptGroup.java

Add a typeid handler to support type id script deploy

feat: 🎸 support type id handler

---

README.md
ckb/src/main/java/org/nervos/ckb/transaction/AbstractTransactionBuilder.java
ckb/src/main/java/org/nervos/ckb/transaction/handler/ScriptHandler.java
core/src/main/java/org/nervos/ckb/sign/ScriptSigner.java
core/src/main/java/org/nervos/ckb/sign/TransactionSigner.java

develop merge master

---

CHANGELOG.md
build.gradle

Bump to 3.0.0.
Invite @doitian to approve this PR and create a new tag.

Bump ckb-sdk-java to 3.0.0

---

.github/workflows/cd.yml
README.md
build.gradle
ckb/src/main/java/org/nervos/ckb/CkbRpcApi.java
ckb/src/main/java/org/nervos/ckb/transaction/AbstractTransactionBuilder.java
ckb/src/main/java/org/nervos/ckb/transaction/CkbTransactionBuilder.java
ckb/src/main/java/org/nervos/ckb/transaction/handler/ScriptHandler.java
core/src/main/java/org/nervos/ckb/sign/ScriptSigner.java

This PR:
1. Fixed javadoc, pom file missing, gpg signature missing.
2. Fix publish to maven steps. (This PR has published 3.0.0-alpha by CI https://central.sonatype.com/artifact/org.nervos.ckb/ckb)
3. Bump to 3.0.1

Fix javadoc, pom file missing, gpg signature error, Bump to 3.0.1
