nervosnetwork/ckb-sdk-java

utils/src/main/java/org/nervos/ckb/crypto/secp256k1/ECKeyPair.java, utils/src/main/java/org/nervos/ckb/crypto/secp256k1/Sign.java, utils/src/test/java/org/nervos/ckb/crypto/secp256k1/SignTest.java
bcprov-jdk15 only stupport uncompressed public key to sign message
=> fix: use uncompressed public key to sign message

core/src/main/java/org/nervos/ckb/methods/type/Script.java, core/src/test/java/type/ScriptTest.java
objectMapper.writeValueAsString will put getter func into json,so send transaction will have a wrong param "typeHash" in APIServiceImpl
=> fix: change getTypeHash to scriptHash

core/src/main/java/org/nervos/ckb/methods/type/Witness.java
fix jackson warning (no suitable constructor found, can not deserialize from Object value)
=> chore: witness add non-parameter constructor

core/src/main/java/org/nervos/ckb/methods/type/Witness.java
fix jackson warning (no suitable constructor found, can not deserialize from Object value)
=> [ᚬrc/v0.13.0] chore: witness add non-parameter constructor

utils/src/main/java/org/nervos/ckb/address/AddressUtils.java, utils/src/test/java/org/nervos/ckb/address/AddressTest.java
BREAKING CHANGE: A public key will derive different address from previous implementation.
As the code hash index has been changed from 4 bytes to 1 byte, the first serveral fixed
characters will become ckt1qyq from ckb1q9gry5zg and be shorter.
https://github.com/nervosnetwork/rfcs/pull/100
=> feat: Update address format generator

ckb/src/main/java/org/nervos/ckb/transaction/TransactionBuilder.java
Now sdk already checks min capacity when collecting cells, so remvoe this `MIN_CAPACITY`
=> [ᚬrc/v0.25.0] Remove useless min capacity

CHANGELOG.md, build.gradle
=> [ᚬmaster] Rc/v0.28.0

example/src/main/java/org/nervos/ckb/transaction/CellBlockIterator.java
- Remove useless null condition
- Clear `cellOutputList` when `cellOutputList` is empty to fix cell collecting fail
=> fix cell collector bug

ckb/src/main/java/org/nervos/ckb/transaction/CellCollector.java
Issue: if there is more than one address and first of the addresses has no live cells, then the witness will be wrong(`0x`), resulting in an error in the calculation of the tx size.
=> fix: wrong tx fee

ckb/src/main/java/org/nervos/ckb/transaction/CellCollector.java
Issue: When passing multiple same addresses to `collectInputs` will cause `outOfBoundsCheckIndex`
=> fix: witnesses update bug

core/src/main/java/org/nervos/ckb/service/RpcService.java
Fix problem that when getting non-successful RPC code,`OKHttpClient` response won't close and then lead memory leak due to the fact that the returned response won't be read.
=> fix: close OK http client

.idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml, ckb/src/main/java/org/nervos/ckb/CkbRpcApi.java, ckb/src/main/java/org/nervos/ckb/service/Api.java, ckb/src/test/java/service/ApiTest.java, core/src/main/java/org/nervos/ckb/type/FeeRateStatics.java, core/src/main/java/org/nervos/ckb/type/TransactionWithStatus.java
1. Disable tests that can not pass in local environment.
2. Support rpc api get_fee_rate_statics
3. Support cycles in rpc api get_transaction
4. Add IDEA codeStyles for the project to share code style through VCS.
[Upgrade SDKs to support CKB v0.106.0 #3726](https://github.com/nervosnetwork/ckb/issues/3726)
=> Feat:support rpc method get fee rate statics

build.gradle, ckb-indexer/src/main/java/org/nervos/indexer/CkbIndexerRpcMethods.java, ckb-indexer/src/main/java/org/nervos/indexer/Configuration.java, ckb-indexer/src/main/java/org/nervos/indexer/DefaultIndexerApi.java, ckb-indexer/src/main/java/org/nervos/indexer/IndexerType.java, ckb-indexer/src/main/java/org/nervos/indexer/InputIterator.java, ckb-indexer/src/test/java/indexer/CkbIndexerFactory.java, ckb-indexer/src/test/java/indexer/TipTest.java
1. Add ignoreFailures = true to make test continue to find more unit test errors.
2. Support get_indexer_tip for ckb module indexer.
3. Add Configuration to config which url to use.
=> feat: 🎸 Make ckb-indexer can configure which api url to use

ckb-indexer/build.gradle, ckb-indexer/src/test/java/indexer/TipTest.java, ckb-mercury-sdk/build.gradle, light-client/build.gradle
1. chore: Update deprecated gradle functions to new ones;
2. test: Disable unittest getTipStandAlone since test indexer point to ckb module
=> Chore: fix auto cd problems

CHANGELOG.md, ckb-indexer/src/main/java/org/nervos/indexer/model/ScriptSearchMode.java, ckb-indexer/src/main/java/org/nervos/indexer/model/SearchKey.java, ckb-indexer/src/main/java/org/nervos/indexer/model/SearchKeyBuilder.java, ckb/src/test/java/service/ApiTest.java, core/src/main/java/org/nervos/ckb/service/RpcService.java
- support indexer search mode
- https://github.com/nervosnetwork/ckb-sdk-java/issues/626
- https://github.com/nervosnetwork/ckb-indexer/pull/64
=> feat: 🎸 support indexer search mode

ckb/src/main/java/org/nervos/ckb/transaction/handler/DaoScriptHandler.java
Make dao handler get correct withdraw phrase 1 block hash.
=> fix: 🐛 Make dao handler get correct withdraw block hash

ckb/src/main/java/org/nervos/ckb/transaction/AbstractTransactionBuilder.java, ckb/src/main/java/org/nervos/ckb/transaction/CkbTransactionBuilder.java, ckb/src/main/java/org/nervos/ckb/transaction/SudtTransactionBuilder.java, ckb/src/main/java/org/nervos/ckb/transaction/TransactionBuilderConfiguration.java, ckb/src/test/java/transaction/CkbTransactionBuilderTest.java, core/src/main/java/org/nervos/ckb/utils/address/Address.java
~Due to existing design/implementation of change output, a change output must not be set when using this feature.~
~Alternatively, we can change the change output implementation a bit and still add a change output when this option is used but the fee is not that small. WDYT?~
Change output is still supported when using forceSmallChangeAsFee.
=> feat: force small change as fee

README.md, ckb/build.gradle
Close #659.
(Targets master because that's the default branch and where people are more likely to see the README.)
=> chore: fix README transaction builder example

ckb/src/main/java/org/nervos/ckb/transaction/AbstractTransactionBuilder.java, ckb/src/main/java/org/nervos/ckb/transaction/handler/ScriptHandler.java, core/src/main/java/org/nervos/ckb/sign/ScriptSigner.java, core/src/main/java/org/nervos/ckb/sign/TransactionSigner.java
Document ScriptHandler and ScriptSigner for custom scripts.
This is based on my experiment here:
https://github.com/doitian/ckb-sdk-examples/blob/main/examples/custom-script/README.java.md
=> docs: document script handler and signer

ckb/src/main/java/org/nervos/ckb/CkbRpcApi.java, ckb/src/main/java/org/nervos/ckb/service/Api.java, ckb/src/main/java/org/nervos/ckb/transaction/TransactionBuilderConfiguration.java, ckb/src/main/java/org/nervos/ckb/transaction/handler/Secp256k1Blake160MultisigAllScriptHandler.java, core/src/main/java/org/nervos/ckb/sign/TransactionSigner.java, core/src/main/java/org/nervos/ckb/type/EntryCompleted.java, core/src/main/java/org/nervos/ckb/type/MultisigVersion.java, core/src/main/java/org/nervos/ckb/type/Script.java, core/src/main/java/org/nervos/ckb/utils/address/Address.java, core/src/test/java/utils/AddressTest.java, example/src/main/java/org/nervos/ckb/example/SendCkbMultisigExample.java
This PR add `MultisigVersion` to ckb-sdk-java:
before
```java
Secp256k1Blake160MultisigAllScriptHandler handler = Secp256k1Blake160MultisigAllScriptHandler();
handler.init();
```
This PR:
```java
public enum MultisigVersion {
/// Multisig Script deployed on Genesis Block
/// https://explorer.nervos.org/script/0x5c5069eb0857efc65e1bca0c07df34c31663b3622fd3876c876320fc9634e2a8/type
Legacy,
/// Latest multisig script, Enhance multisig handling for optional since value
/// https://github.com/nervosnetwork/ckb-system-scripts/pull/99
/// https://explorer.nervos.org/script/0x36c971b8d41fbd94aabca77dc75e826729ac98447b46f91e00796155dddb0d29/data1
V2;
Secp256k1Blake160MultisigAllScriptHandler handler = Secp256k1Blake160MultisigAllScriptHandler(MultisigVersion::Legacy);
handler.init();
```
Invite …
=> [BREAKING CHANGE] Add `MultisigVersion` `Legacy` and `V2`
